### ISSUE TITLE
Исправить pages в json ответе

### ISSUE THREAD

**Issue by rocketmannot** [Artiomtb/StatisticsServer#12]
pages в json должен показывать количество доступных страниц. Также нужно добавить current_page, узел который показывает номер текущей страницы. Нужно сделать для Students  и для Pubs
Пример:
```
{
    "pages": 100,
    "current_page": 100,
    "pubs": [{"pub_name": "test", "pub_id": 1},{"pub_name": "test", "pub_id": 2}]
}
```

**Comment by Artiomtb** [comment]
Implemented
