### ISSUE TITLE
URGENT Функционал обновления графа связей

### ISSUE THREAD

**Issue by Artiomtb** [Artiomtb/StatisticsServer#15]
Добавить слайдер под граф связей, дающий юзеру возможность выставить количество времени в минутах, при котором связь считается таковой. 
Интервал: 1-30 минут.
Данные должны обновляться с помощью AJAX.
Добавить прогресс бар при обновлении данных : http://getbootstrap.com/components/#progress (Animated)
Запрос выполнять по ссылке /monitor/general/pub/links?pub_id=?&link_time=?

**Comment by rocketmannot** [comment]
implemented
